"""Regenerate the four graphite concept pages from editable copy and SVG assets."""
from pathlib import Path
import re

OUT = Path(__file__).parent / 'dist'
ASSETS = OUT / 'assets'
PAGES = [('home','index.html','North State'),('manufacturing','manufacturing.html','Manufacturing'),('powder','powder-coating.html','Powder Coating'),('academy','academy.html','Academy')]
SCENES = {'manufacturing':'manufacturing-isometric.svg','powder':'powder-coating-isometric.svg','academy':'academy-classroom-isometric.svg'}
TITLES = {'manufacturing':'A top-down isometric machining and fabrication workshop','powder':'A top-down isometric powder coating workspace','academy':'A top-down isometric powder coating classroom with demonstration bench and six student workstations'}

def scene(kind, instance, href=None, caption=None):
    raw = (ASSETS / SCENES[kind]).read_text(encoding='utf-8')
    raw = raw[raw.index('<svg'):]
    # Each inline instance needs its own accessible title and filter identifiers.
    ids = re.findall(r'\bid="([^"]+)"', raw)
    for ident in ids:
        raw = raw.replace(f'id="{ident}"', f'id="{instance}-{ident}"').replace(f'url(#{ident})', f'url(#{instance}-{ident})').replace(f'href="#{ident}"', f'href="#{instance}-{ident}"')
    raw = re.sub(r'\saria-labelledby="[^"]*"', '', raw)
    raw = re.sub(r'\srole="[^"]*"', '', raw)
    raw = raw.replace('<svg ', f'<svg role="img" aria-label="{TITLES[kind]}" ', 1)
    drawing = f'<div class="drawing-stage" data-scene="{kind}">{raw}<span class="drawing-caption" aria-hidden="true">North State / {kind} study</span></div>'
    if href:
        drawing = f'<a class="drawing-link" href="{href}" aria-label="Explore {dict((p[0],p[2]) for p in PAGES)[kind]}">{drawing}</a>'
    return f'<figure class="island-art">{drawing}<figcaption class="figure-caption"><span>{caption or "ISOMETRIC STUDY / " + kind.upper()}</span><span>Conceptual workspace<br>View from above ↗</span></figcaption></figure>'

def shell(key, title, desc, body):
    links = ''.join(f'<a href="{url}"'+(' aria-current="page"' if key==k else '')+f'>{name}'+(' <small>2027</small>' if k=='academy' else '')+'</a>' for k,url,name in PAGES)
    return f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#23262A"><meta name="description" content="{desc}"><title>{title} — North State</title><link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 40 40'%3E%3Cpath fill='%2323262a' stroke='%238d9498' d='M1 1h38v38H1z'/%3E%3Cpath fill='none' stroke='%23dedcd3' stroke-width='2' d='M11 29V11L29 29V11'/%3E%3C/svg%3E"><link rel="stylesheet" href="northstate.css"><script src="northstate.js" defer></script></head>
<body data-page="{key}"><a class="skip-link" href="#main">Skip to content</a>
<header class="masthead"><span class="meta">North Carolina<br>United by craft</span><a class="brand" href="index.html" aria-label="North State home"><img src="assets/northstate-group-graphite.svg" width="2003" height="910" alt="North State"></a><span class="meta">Make / Finish / Teach<br>One North State</span></header>
<nav class="site-nav" aria-label="Main navigation"><button class="menu-toggle" aria-expanded="false" aria-controls="main-menu">Explore North State <span aria-hidden="true">+</span></button><div class="nav-links" id="main-menu">{links}</div></nav>
<main id="main">{body}</main>
<footer class="site-footer"><div>NORTH STATE / MAKE. FINISH. PASS IT ON.<br>Graphite series · Website concept</div><div class="footer-links"><a href="blueprint.html#whiteprint-dark">Style guide ↗</a><a href="concepts.html">Original studies ↗</a><a href="assets/North-State-Graphite-Site-Guide.md" download>Designer notes ↓</a></div></footer>
</body></html>'''

def eyebrow(text): return f'<span class="eyebrow">{text}</span>'
def row(num, title, text): return f'<article class="editorial-row reveal"><span class="meta">{num}</span><h3>{title}</h3><p>{text}</p></article>'
def next_links(keys):
    return '<nav class="next-division" aria-label="Explore another division">'+''.join(f'<a href="{url}"><div><span class="meta">Continue exploring</span><h3>{name}</h3></div><span class="next-arrow" aria-hidden="true">↗</span></a>' for k,url,name in PAGES if k in keys)+'</nav>'
def contact(title='Let’s make something<br><em>worth keeping.</em>', copy='A part to make. A surface to protect. Start with a conversation.', subject='North State project enquiry'):
    return f'''<section class="contact-island reveal" id="contact">{eyebrow('Next / your project')}<h2>{title}</h2><p>{copy}</p><a class="text-link" href="mailto:Jesse@northstatepc.com?subject={subject.replace(' ','%20')}">Tell us what you have in mind <span aria-hidden="true">↗</span></a><div class="contact-links"><a href="mailto:Jesse@northstatepc.com">Jesse@northstatepc.com</a><a href="tel:+19198012079">(919) 801-2079</a><address>1305 Graham St<br>Burlington, North Carolina</address></div></section>'''

def home():
    data=[('manufacturing','01','Manufacturing.','From the first drawing<br><em>to the finished part.</em>','Machining and fabrication, brought together around the details that make your project work.','Explore Manufacturing',['Machining','Fabrication']),('powder','02','Powder coating.','A considered finish.<br><em>A lasting impression.</em>','Professional powder coating for metal surfaces, industrial equipment, and the pieces that need to stand up to everyday wear.','Explore Powder Coating',['Protection','Surface finish']),('academy','03','Academy.','Good work deserves<br><em>to be passed on.</em>','A new place to learn the craft of powder coating. From surface preparation to the finished piece, follow the next chapter of North State.','Step inside the Academy',['Powder coating education','Coming 2027'])]
    islands=''
    for kind,num,name,heading,copy,cta,tags in data:
        url=next(p[1] for p in PAGES if p[0]==kind)
        islands+=f'''<section class="division-island" data-island id="{kind}"><div class="island-copy reveal">{eyebrow(f'{num} / {name}')}<h2>{heading}</h2><p>{copy}</p><a class="text-link" href="{url}">{cta}<span aria-hidden="true">↗</span></a><div class="island-meta">{''.join(f'<span class="tag">{t}</span>' for t in tags)}</div></div>{scene(kind,'home-'+kind,url,f'NS / {num} — {name.upper()}')}</section>'''
    body=f'''<div class="frame"><section class="page-intro"><span class="eyebrow intro-index">Three disciplines. One shared purpose.</span><h1 class="home-title">Made with purpose.<br><em>Connected by craft.</em></h1><p>We make. We finish. We pass it on.<br>Follow the thread through North State.</p><a class="intro-foot" href="#manufacturing">Explore our worlds <span class="down" aria-hidden="true">↓</span></a></section><div class="journey" data-journey><svg class="journey-line" aria-hidden="true"></svg>{islands}</div>{contact()}{next_links(['manufacturing','powder'])}</div>'''
    return shell('home','Made with purpose','Explore North State Manufacturing, Powder Coating, and Academy. Three disciplines connected by craft.',body)

def branch_hero(kind, kicker, title, text, action, target):
    name=next(p[2] for p in PAGES if p[0]==kind)
    return f'''<div class="breadcrumb"><a href="index.html">North State</a><span aria-hidden="true">/</span><span>{name}</span></div><section class="branch-hero"><div class="hero-copy reveal">{eyebrow(kicker)}<h1>{title}</h1><p>{text}</p><a class="text-link" href="#{target}">{action} <span aria-hidden="true">↘</span></a></div>{scene(kind,kind+'-hero')}</section>'''

def manufacturing():
    hero=branch_hero('manufacturing','01 / North State Manufacturing','An idea.<br>A drawing.<br><em>A real thing.</em>','Machining and fabrication for the parts, assemblies, and practical details that bring your project together.','Explore the work','capabilities')
    content=f'''<div class="chapter-rule"><strong>MACHINING / FABRICATION</strong><span>From a working drawing to a working part.</span></div><section class="content-chapter" id="capabilities"><div class="chapter-header reveal"><div>{eyebrow('01 / What we make possible')}<h2>Precision meets<br><em>practical craft.</em></h2></div><p>Every project starts with a purpose. The material, the shape, the fit—each detail has a job to do.</p></div><div class="editorial-rows">{row('I','Machining.','Turn a drawing into a component. Bring the geometry, material, and fit into focus, from a single part to a larger assembly.')}{row('II','Fabrication.','Bring metal into form. Cut, shape, and join the elements that make a useful structure, fixture, or finished piece.')}{row('III','A connected finish.','Think beyond the part itself. Explore powder coating where a protective surface is part of the brief.')}</div></section>
    <section class="content-chapter" data-explorer><div class="detail-explorer">{scene('manufacturing','manufacturing-detail',caption='DETAIL STUDY / THE WORKSHOP')}<div class="detail-copy reveal">{eyebrow('02 / Inside the workshop')}<h2>Look closer.<br><em>Every detail matters.</em></h2><p>Explore the relationships between material, machining, and assembly.</p><div class="legend-controls"><button class="legend-control" data-highlight="machining" data-caption="Machining: a controlled space for shaping and refining a component." aria-pressed="false">01 / Machining <span>+</span></button><button class="legend-control" data-highlight="fabrication" data-caption="Fabrication: the workbench is where individual elements become an assembly." aria-pressed="false">02 / Fabrication <span>+</span></button><button class="legend-control" data-highlight="materials" data-caption="Materials: stock, offcuts, and parts arranged around the work." aria-pressed="false">03 / Materials <span>+</span></button></div><p class="explorer-caption" aria-live="polite">Select a detail to study the drawing. Illustrative workspace, not a plan of the actual facility.</p></div></div></section>
    {contact('Your next part.<br><em>Let’s give it form.</em>','Have a drawing, a sample, or a problem to solve? Tell us about the material, the application, and what the part needs to do.','Manufacturing project enquiry')}{next_links(['powder','academy'])}'''
    return shell('manufacturing','Machining & fabrication','Explore North State Manufacturing: machining, fabrication, and considered metalwork.',f'<div class="frame">{hero}{content}</div>')

def powder():
    hero=branch_hero('powder','02 / North State Powder Coating','Good metal.<br><em>Considered<br>finish.</em>','Professional powder coating for metal surfaces. Protective finishing, custom solutions, and a personal approach.','Follow the process','process')
    content=f'''<div class="chapter-rule"><strong>BURLINGTON, NORTH CAROLINA</strong><span>Local service. Lasting care.</span></div><section class="content-chapter" id="process"><div class="chapter-header reveal"><div>{eyebrow('01 / The finishing practice')}<h2>It starts beneath<br><em>the surface.</em></h2></div><p>A finish is a sequence of considered steps. Preparation, application, and curing work together to protect the metal underneath.</p></div><div class="editorial-rows">{row('I','Prepare.','A clean, properly prepared surface is the foundation. Preparation is chosen for the material and the finish it needs.')}{row('II','Apply.','Powder is applied to the surface to form a uniform coating. The part’s shape and application guide the approach.')}{row('III','Cure & inspect.','The applied powder is cured into a continuous film. The finished piece is checked before it returns to work.')}</div></section>
    <section class="content-chapter" data-explorer><div class="detail-explorer">{scene('powder','powder-detail',caption='DETAIL STUDY / THE FINISHING SPACE')}<div class="detail-copy reveal">{eyebrow('02 / Built around the surface')}<h2>One finish.<br><em>A connected process.</em></h2><p>From hanging a part to its final finish, each area supports the next.</p><div class="legend-controls"><button class="legend-control" data-highlight="booth" data-caption="Application: the booth provides a defined workspace around the coating process." aria-pressed="false">01 / Application space <span>+</span></button><button class="legend-control" data-highlight="rail" data-caption="Part handling: hanging components keeps their surfaces accessible during finishing." aria-pressed="false">02 / Part handling <span>+</span></button><button class="legend-control" data-highlight="oven" data-caption="Curing: heat transforms the applied powder into a continuous coating film." aria-pressed="false">03 / Curing <span>+</span></button></div><p class="explorer-caption" aria-live="polite">Select a detail to study the drawing. Illustrative workflow, not a plan of North State’s actual equipment.</p></div></div></section>
    <section class="content-chapter"><div class="chapter-header reveal"><div>{eyebrow('03 / What the finish does')}<h2>A little protection.<br><em>A longer story.</em></h2></div><p>Coating solutions for industrial machinery, equipment, and metal projects, with attention to corrosion, wear, and the final appearance.</p></div></section>{contact('Let’s give your metal<br><em>a new beginning.</em>','Tell us what you’re coating, where it will be used, and the finish you have in mind.','Powder coating enquiry')}{next_links(['manufacturing','academy'])}'''
    return shell('powder','Powder coating','Professional powder coating in Burlington, North Carolina. Custom coating solutions and protective finishing for metal surfaces.',f'<div class="frame">{hero}{content}</div>')

POSTS=[
 {'id':'surface','num':'01','category':'Surface preparation','time':'1 MIN READ','title':'A good finish starts before the first coat.','excerpt':'Why the surface beneath the powder deserves as much attention as the finish itself.','paragraphs':['A finished surface catches the eye. The work that makes it possible often happens earlier, while the metal still looks unfinished.','Surface preparation is about creating a foundation for the coating. Material condition, contamination, and the intended use of the part all matter. In a classroom, learning to notice those differences is as valuable as learning the vocabulary.','The first lesson is simple: look closely, ask questions, and understand the condition of the part before choosing the next step. Good observation is a skill worth practicing.']},
 {'id':'samples','num':'02','category':'The learning bench','time':'1 MIN READ','title':'Small samples. Useful lessons.','excerpt':'A sample panel can open a bigger conversation about texture, consistency, and care.','paragraphs':['A small sample is a useful place to begin a big conversation. Held side by side, simple panels make differences in appearance easier to see and discuss.','A learning bench brings those comparisons into focus. Students can describe texture, reflect on surface condition, and connect what they observe to the stages of a finishing process.','The goal is not to rush to a perfect result. It is to learn how to look, compare, and ask a better next question.']},
 {'id':'classroom','num':'03','category':'Academy notes','time':'1 MIN READ','title':'A classroom built around the craft.','excerpt':'A look at the thinking behind a place to observe, discuss, and learn powder coating.','paragraphs':['Some things make more sense when you can see them from more than one angle. A teaching space can connect the explanation at the board with the material on the bench.','This Academy concept pairs small workstations with a shared demonstration area. The layout gives ideas a place to move: from an instructor’s explanation to a sample, a question, and a discussion.','As the Academy develops, the ambition is to make the craft approachable while giving each stage of the process the attention it deserves.']}
]

def academy():
    hero=branch_hero('academy','03 / North State Academy — Coming 2027','Learn the craft.<br><em>Make it<br>your own.</em>','A new chapter in powder coating education. A place to understand the process, study the details, and build confidence in the craft.','Step into the classroom','classroom')
    posts=''.join(f'''<article class="journal-card reveal"><div class="journal-meta"><span>SAMPLE ENTRY / {p['num']}</span><span>{p['time']}</span></div><span class="journal-number" aria-hidden="true">{p['num']}</span><span class="eyebrow">{p['category']}</span><h3>{p['title']}</h3><p>{p['excerpt']}</p><button data-article="{p['id']}" aria-haspopup="dialog">Read the sample <span aria-hidden="true">↗</span></button></article>''' for p in POSTS)
    templates=''.join(f'''<template id="article-{p['id']}"><span class="meta">SAMPLE JOURNAL / {p['category'].upper()} / {p['time']}</span><h2 id="article-title">{p['title']}</h2>{''.join(f'<p>{t}</p>' for t in p['paragraphs'])}<p class="demo-note">Fictional editorial content for this website concept. This is not an operating procedure or a published Academy curriculum.</p></template>''' for p in POSTS)
    content=f'''<section class="release-section" id="release"><div><span class="meta">A new chapter / 2027</span><h2>The next chapter<br><em>is taking shape.</em></h2><div class="countdown" role="timer" aria-label="Time until the Academy demo launch target"><div><strong data-count="days">—</strong><span>Days</span></div><div><strong data-count="hours">—</strong><span>Hours</span></div><div><strong data-count="minutes">—</strong><span>Minutes</span></div><div><strong data-count="seconds">—</strong><span>Seconds</span></div></div><p class="release-note">Demo launch target: January 1, 2027 · 00:00 Eastern<br>Exact opening date to be confirmed.</p></div><div><span class="meta">Academy in the making</span><div class="progress-heading"><label for="academy-progress">A work in progress.</label><output id="progress-value" for="academy-progress">52%</output></div><input class="progress-slider" id="academy-progress" type="range" min="0" max="100" value="52" step="1" aria-describedby="progress-description"><div class="progress-labels"><span>THE IDEA</span><span>TAKING SHAPE</span><span>DOORS OPEN</span></div><p id="progress-description" class="progress-description">An illustrative progress slider for the concept. Drag to explore; this is not a live construction or curriculum status.</p><button class="progress-reset" type="button">Reset to 52%</button></div></section>
    <section class="content-chapter" id="classroom" data-explorer><div class="chapter-header reveal"><div>{eyebrow('01 / A place to learn')}<h2>From the board<br><em>to the workbench.</em></h2></div><p>A classroom imagined around powder coating: space to see a demonstration, study sample panels, and work through the process together.</p></div><div class="detail-explorer">{scene('academy','academy-detail',caption='CLASSROOM STUDY / VIEW FROM ABOVE')}<div class="detail-copy"><div class="legend-controls"><button class="legend-control" data-highlight="desks" data-caption="Student workstations: small groups, shared questions, and room for sample panels and notes." aria-pressed="false">01 / Student workstations <span>+</span></button><button class="legend-control" data-highlight="demonstration" data-caption="Demonstration bench: a shared view of the tools, surfaces, and ideas behind the coating process." aria-pressed="false">02 / Demonstration bench <span>+</span></button><button class="legend-control" data-highlight="materials" data-caption="The sample library: a place to compare finishes and connect observations with what you are learning." aria-pressed="false">03 / Sample library <span>+</span></button></div><p class="explorer-caption" aria-live="polite">Select an area to explore the classroom. This is an illustrative teaching space, not a confirmed floor plan.</p></div></div></section>
    <section class="content-chapter"><div class="chapter-header reveal"><div>{eyebrow('02 / The learning direction')}<h2>Understand the process.<br><em>Notice the difference.</em></h2></div><p>A proposed learning path built around the fundamentals of powder coating.</p></div><div class="editorial-rows">{row('I','Surface & preparation.','Recognize the substrate, understand why surface condition matters, and connect preparation with coating performance.')}{row('II','Powder & application.','Build familiarity with coating materials, application equipment, and the way a part’s shape affects the work.')}{row('III','Cure & quality.','Understand the role of curing and develop an eye for the appearance and consistency of a finished surface.')}</div><p class="demo-note">Academy concept: topics are illustrative. Course formats, curriculum, enrollment, and the opening date will be announced when confirmed.</p></section>
    <section class="content-chapter" id="journal"><div class="journal-header reveal"><div>{eyebrow('03 / From the Academy journal')}<h2>Notes from<br><em>the learning bench.</em></h2></div><p class="inline-note">A preview of the editorial direction.<br>Three fictional articles for this demo.</p></div><div class="journal-grid">{posts}</div></section>
    {contact('Curious about<br><em>what comes next?</em>','For Academy enquiries, start a conversation with North State.','Academy enquiry')}{next_links(['manufacturing','powder'])}
    <dialog class="article-dialog" aria-labelledby="article-title"><button class="article-close" aria-label="Close article">×</button><div class="article-content"></div></dialog>{templates}'''
    return shell('academy','Powder Coating Academy · 2027','Explore the North State Powder Coating Academy concept: a learning space, sample journal, and a look ahead to 2027.',f'<div class="frame">{hero}{content}</div>')

if __name__ == '__main__':
    for name, render in [('index.html',home),('manufacturing.html',manufacturing),('powder-coating.html',powder),('academy.html',academy)]:
        (OUT/name).write_text(render(), encoding='utf-8')
        print(name)
